name: Release Obsidian plugin

on:
  release:
    types: [published] 

permissions:
  contents: write   

env:
  PLUGIN_NAME: smart-fold

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci || npm install

      - name: Build
        run: npm run build

      - name: Package plugin (folder + zip)
        run: |
          mkdir -p "${{ env.PLUGIN_NAME }}"
          cp manifest.json main.js "${{ env.PLUGIN_NAME }}/"
          zip -r "${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip" "${{ env.PLUGIN_NAME }}"

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref_name }}
          files: |
            ${{ env.PLUGIN_NAME }}-${{ github.ref_name }}.zip
            main.js
            manifest.json
